### ISSUE TITLE
APEX

### ISSUE THREAD

**Issue by Kanarskq** [oleksandrblazhko/ai-211-kanarskij#26]
Прошу надати можливість віддаленого доступу до серверу Oracle

**Comment by oleksandrblazhko** [comment]
Доброго дня.
На Oracle-севері для вас створено обліковий запис:
login = kanarskij
password = p1P34ab#

Приклад встановлення з'єднання через SQLPlus:
sqlplus kanarskij/p1P34ab#@185.235.218.67:1521/XEPDB1

Приклад програмного коду java-програми із
методами доступу до Oracle БД наведено
в лабораторній роботі.
